name       : python-future
version    : 0.16.0
release    : 1
source     :
    - https://github.com/PythonCharmers/python-future/archive/v0.16.0.tar.gz : 904dfd0bbc36b5d82879d0dc9ced84fa1b6d4c621e7a7dbf9efeb61561e1d637
license    : MIT
component  : programming.python
summary    : Clean single-source support for Python 3 and 2
description: |
    python-future is the missing compatibility layer between Python 2 and Python 3.
    It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
extract    : no
setup      : |
    # Not having separate directories causes a build error
    tar -zxf $sources/v$version.tar.gz -C $workdir
    mv $workdir/python-future-$version $workdir/python-future-$version-2
    tar -zxf $sources/v$version.tar.gz -C $workdir
build      : |
    cd $workdir/python-future-$version-2
    %python_setup
    cd $workdir/python-future-$version
    %python3_setup
install    : |
    cd "$workdir"/python-future-$version-2
    %python_install
    cd "$workdir"/python-future-$version
    %python3_install