name       : python-future
version    : 0.18.3
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/f/future/future-0.18.3.tar.gz : 34a17436ed1e96697a86f9de3d15a3b0be01d8bc8de9c1dffd59fb8234ed5307
homepage   : https://python-future.org/
license    : MIT
component  : programming.python
summary    : Clean single-source support for Python 3 and 2
description: |
    python-future is the missing compatibility layer between Python 2 and Python 3. It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.
networking : yes
builddeps  :
    - python-pytest
    - python-requests
setup      : |
    %apply_patches
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
