name       : python-future
version    : 0.17.0
release    : 3
source     :
    - https://github.com/PythonCharmers/python-future/archive/v0.17.0.tar.gz : 2cb1937234201b12447e7e777096d6cd616b00b7553b44cdf18518b0dbb02dce
license    : MIT
component  : programming.python
summary    : Clean single-source support for Python 3 and 2
description: |
    python-future is the missing compatibility layer between Python 2 and Python 3.
    It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
