name       : python-future
version    : 0.16.0
release    : 2
source     :
    - https://github.com/PythonCharmers/python-future/archive/v0.16.0.tar.gz : 904dfd0bbc36b5d82879d0dc9ced84fa1b6d4c621e7a7dbf9efeb61561e1d637
license    : MIT
component  : programming.python
summary    : Clean single-source support for Python 3 and 2
description: |
    python-future is the missing compatibility layer between Python 2 and Python 3.
    It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
