name       : python-future
version    : 0.18.2
release    : 6
source     :
    - https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz : b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d
homepage   : https://python-future.org/
license    : MIT
component  : programming.python
summary    : Clean single-source support for Python 3 and 2
description: |
    python-future is the missing compatibility layer between Python 2 and Python 3. It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead.
networking : yes
builddeps  :
    - python-pytest
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
